spring:
  profile: a
  spplication:
    name: spring-cloud-config-3344-dev
---
spring:
  profile: b
  spplication:
    name: spring-cloud-config-3344-dev
---
spring:
  profile: c
  spplication:
    name: spring-cloud-config-3344-dev
