spring:
  profile:
    active:
<<<<<<< HEAD
    -dev
=======
    - dev
>>>>>>> parent of 3c3775a... Update application.yml
---
spring:
  profile: dev
  spplication:
    name: spring-cloud-config-3344-dev
---
spring:
  profile: test
  appplication:
    name: spring-cloud-config-3344-test